test_that("classify_tree_markers matches root and .github entries, tags agents-md agnostic", {
  out <- classify_tree_markers(c("CLAUDE.md", ".cursor", "README.md", "AGENTS.md"),
                               c("copilot-instructions.md", "workflows"))
  expect_setequal(out$tool, c("claude", "cursor", "copilot", "agents-md"))
  expect_true(all(out$tier == "D"))
  expect_true(out$agnostic[out$tool == "agents-md"])
  expect_false(any(out$agnostic[out$tool != "agents-md"]))
})

test_that("classify_tree_markers does not match a github-located marker at root", {
  out <- classify_tree_markers(c("copilot-instructions.md"), character(0))
  expect_equal(nrow(out), 0)   # copilot marker only counts inside .github
})

test_that("classify_tree_markers returns typed empty frame when nothing matches", {
  out <- classify_tree_markers(c("R", "man", "DESCRIPTION"), c("workflows"))
  expect_equal(nrow(out), 0)
  expect_true(all(c("tool","tier","marker","agnostic") %in% names(out)))
})

test_that("scan_ignore_tokens anchors whole entries and ignores comments and word-substrings", {
  gi <- c("# ai stuff", ".aiderignore", "*.o", "codex_output/")   # codex_output must NOT match codex
  rb <- c("^\\.cursor$", ".cursorignore")
  out <- scan_ignore_tokens(gi, rb)
  expect_true("aider" %in% out$tool)                         # .aiderignore is a real AI_MARKERS aider path
  expect_true("cursor" %in% out$tool)
  expect_false("codex" %in% out$tool)                        # substring collision rejected
  expect_true(all(grepl("^ignore:", out$marker)))
})

test_that("scan_ignore_tokens returns typed empty frame on no match", {
  out <- scan_ignore_tokens(c("*.tmp", "# nothing"), character(0))
  expect_equal(nrow(out), 0)
  expect_true(all(c("tool","tier","marker","agnostic") %in% names(out)))
})

test_that("match_bot_identity matches allowlist exactly, rejects denylist and lookalikes", {
  out <- match_bot_identity(c("NoReply@Anthropic.com", "someone@example.com"),
                            c("dependabot[bot]", "devin-ai-integration[bot]"))
  expect_setequal(out$tool, c("claude", "devin"))
  expect_true(all(out$tier == "A"))
  # a lookalike substring must not match
  expect_equal(nrow(match_bot_identity("noreply@anthropic.com.evil.net", character(0))), 0)
  # denylisted bot alone yields nothing
  expect_equal(nrow(match_bot_identity(character(0), "renovate[bot]")), 0)
})

test_that("scan_trailers requires the canonical identity, rejects a human named Claude", {
  yes <- scan_trailers(c("feat: x\n\nCo-authored-by: Claude <noreply@anthropic.com>"))
  expect_equal(yes$tool, "claude"); expect_equal(yes$tier, "B")
  no <- scan_trailers("fix\n\nCo-authored-by: Claude Dupont <claude@univ.fr>")
  expect_equal(nrow(no), 0)
  expect_equal(scan_trailers("chore: generated by Replit")$tool, "replit")
})

test_that("match_author_suffix flags the (aider) suffix only", {
  expect_equal(match_author_suffix(c("Jane Doe (aider)", "Bob"))$tool, "aider")
  expect_equal(nrow(match_author_suffix("aidermann")), 0)
})

test_that("detect_pr_agents matches agent logins, never generic bots", {
  out <- detect_pr_agents(c("Copilot", "dependabot[bot]", "cursor[bot]"))
  expect_setequal(out$tool, c("copilot", "cursor"))
  expect_true(all(out$tier == "PR"))
})

mk <- function(tool, date, censored = 0L, tiers, authored = 0L, agnostic = FALSE)
  data.frame(tool = tool, first_seen_date = date, first_seen_censored = censored,
             evidence_tiers = tiers, authored = authored, agnostic = agnostic,
             stringsAsFactors = FALSE)

test_that("naming threshold: Tier A alone passes, lone Tier D fails, two tiers pass", {
  expect_true(meets_naming_threshold(mk("claude", "2024-01-01", tiers = "A")))
  expect_false(meets_naming_threshold(mk("cursor", "2024-01-01", tiers = "D")))
  expect_true(meets_naming_threshold(mk("claude", "2024-01-01", tiers = "D,B")))
  # agents-md alone never satisfies (agnostic, single tier)
  expect_false(meets_naming_threshold(mk("agents-md", "2024-01-01", tiers = "D", agnostic = TRUE)))
})

test_that("order_ai_tools sorts by date then censored then tier then name, excludes agents-md", {
  rows <- rbind(
    mk("copilot",   "2024-11-01", tiers = "D"),
    mk("claude",    "2024-06-01", tiers = "A"),
    mk("agents-md", "2024-01-01", tiers = "D", agnostic = TRUE),
    mk("cursor",    "2025-03-01", tiers = "D"))
  expect_equal(order_ai_tools(rows), c("claude", "copilot", "cursor"))  # agents-md dropped, chronological
})

test_that("order_ai_tools tie-break: same date -> stronger tier, then name", {
  rows <- rbind(
    mk("cursor", "2024-01-01", tiers = "D"),
    mk("claude", "2024-01-01", tiers = "A"))
  expect_equal(order_ai_tools(rows)[1], "claude")   # A beats D on the same date
})

row <- function(tool, date, cens, tiers, auth, last, repo = "github.com/o/r")
  data.frame(repo_id = repo, tool = tool, first_seen_date = date, first_seen_censored = cens,
             evidence_tiers = tiers, authored = auth, last_confirmed_date = last,
             stringsAsFactors = FALSE)

test_that("reducer: exact replaces a looser floor, tiers union, authored OR, last_confirmed max", {
  prior <- row("claude", "2024-06-01", 1L, "D", 0L, "2024-06-01")            # censored floor <= 2024-06-01
  inc   <- row("claude", "2024-03-01", 0L, "B", 1L, "2025-01-01")            # exact, earlier than floor
  out <- ai_onset_reducer(prior, inc)
  expect_equal(out$first_seen_date, "2024-03-01")
  expect_equal(out$first_seen_censored, 0L)
  expect_setequal(strsplit(out$evidence_tiers, ",")[[1]], c("B", "D"))
  expect_equal(out$authored, 1L)
  expect_equal(out$last_confirmed_date, "2025-01-01")
})

test_that("reducer: two floors tighten to the min; two exacts take the min", {
  o <- ai_onset_reducer(row("cursor","2023-01-01",1L,"D",0L,"2023-01-01"),
                        row("cursor","2022-06-01",1L,"D",0L,"2022-06-01"))
  expect_equal(o$first_seen_date, "2022-06-01"); expect_equal(o$first_seen_censored, 1L)
  e <- ai_onset_reducer(row("cursor","2022-01-01",0L,"D",0L,"2022-01-01"),
                        row("cursor","2021-05-05",0L,"B",0L,"2021-05-05"))
  expect_equal(e$first_seen_date, "2021-05-05"); expect_equal(e$first_seen_censored, 0L)
})

test_that("reducer: an exact LATER than a floor is a contradiction - keep the floor and warn", {
  expect_warning(
    o <- ai_onset_reducer(row("claude","2023-01-01",1L,"D",0L,"2023-01-01"),   # floor <= 2023-01-01
                          row("claude","2024-05-05",0L,"B",0L,"2024-05-05")),   # exact 2024 (contradicts)
    "contradiction")
  expect_equal(o$first_seen_date, "2023-01-01"); expect_equal(o$first_seen_censored, 1L)
})

test_that("reducer keeps distinct tools as distinct rows", {
  o <- ai_onset_reducer(row("claude","2024-01-01",0L,"A",0L,"2024-01-01"),
                        row("cursor","2024-02-01",0L,"D",0L,"2024-02-01"))
  expect_equal(nrow(o), 2)
})

test_that("build_ai_rollups names only threshold-met repos, excludes agents-md from counts", {
  ai <- rbind(
    # repo A: claude Tier A (nameable) + agents-md agnostic
    data.frame(repo_id="github.com/a/a", tool="claude", first_seen_date="2024-06-01",
               first_seen_censored=0L, evidence_tiers="A", authored=1L,
               last_confirmed_date="2025-01-01", stringsAsFactors=FALSE),
    data.frame(repo_id="github.com/a/a", tool="agents-md", first_seen_date="2024-01-01",
               first_seen_censored=0L, evidence_tiers="D", authored=0L,
               last_confirmed_date="2024-01-01", stringsAsFactors=FALSE),
    data.frame(repo_id="github.com/a/a", tool="cursor", first_seen_date="2025-03-01",
               first_seen_censored=0L, evidence_tiers="D,B", authored=0L,
               last_confirmed_date="2025-03-01", stringsAsFactors=FALSE),
    # repo B: lone Tier D -> below threshold, omitted
    data.frame(repo_id="github.com/b/b", tool="copilot", first_seen_date="2024-02-01",
               first_seen_censored=0L, evidence_tiers="D", authored=0L,
               last_confirmed_date="2024-02-01", stringsAsFactors=FALSE))
  out <- build_ai_rollups(ai)
  expect_equal(out$repo_id, "github.com/a/a")            # only the nameable repo
  expect_true(out$ai_markers_detected)
  expect_equal(out$ai_first_tool, "claude")             # earliest non-agnostic
  expect_equal(out$ai_first_date, "2024-06-01")
  expect_equal(out$ai_tool_count, 2L)                   # claude + cursor, agents-md excluded
  expect_equal(out$ai_tools, "claude,cursor")
  expect_equal(out$ai_latest_tool, "cursor")
  expect_equal(out$ai_latest_date, "2025-03-01")
})

test_that("build_ai_rollups returns a typed empty frame when nothing is nameable", {
  ai <- data.frame(repo_id="github.com/b/b", tool="copilot", first_seen_date="2024-02-01",
                   first_seen_censored=0L, evidence_tiers="D", authored=0L,
                   last_confirmed_date="2024-02-01", stringsAsFactors=FALSE)
  out <- build_ai_rollups(ai)
  expect_equal(nrow(out), 0)
  expect_true(all(c("repo_id","ai_markers_detected","ai_first_tool","ai_first_date",
                    "ai_tool_count","ai_tools","ai_latest_tool","ai_latest_date") %in% names(out)))
})

test_that("order_ai_tools does not crash on an unknown evidence_tiers code and sorts it last", {
  rows <- rbind(
    mk("claude", "2024-01-01", tiers = "A"),
    mk("mystery", "2024-01-01", tiers = "Z"))   # unknown tier code -> rank falls back to 99
  out <- order_ai_tools(rows)
  expect_equal(out, c("claude", "mystery"))     # same date: unknown-tier tool included, sorted last on rank
})

test_that("reducer: authored is 0L (never NA) when one input row has authored = NA and none is 1", {
  o <- ai_onset_reducer(row("claude", "2024-01-01", 0L, "A", NA_integer_, "2024-01-01"),
                        row("claude", "2024-02-01", 0L, "B", 0L, "2024-02-01"))
  expect_identical(o$authored, 0L)
  expect_false(is.na(o$authored))
})

test_that("ai_onset_reducer(NULL, NULL) returns a typed 0-row frame, not NULL", {
  out <- ai_onset_reducer(NULL, NULL)
  expect_false(is.null(out))
  expect_equal(nrow(out), 0)
  expect_true(all(c("repo_id", "tool", "first_seen_date", "first_seen_censored",
                    "evidence_tiers", "authored", "last_confirmed_date") %in% names(out)))
})

gd <- function(tool, tier, marker) data.frame(tool = tool, tier = tier, marker = marker,
  agnostic = FALSE, stringsAsFactors = FALSE)

test_that("apply_fork_guard censors every Tier-D marker on a fork", {
  ev <- rbind(gd("claude", "D", ".claude"), gd("cursor", "D", ".cursor"))
  out <- apply_fork_guard(ev, is_fork = TRUE, parent = "up/stream", first_commit_touches = character(0))
  expect_equal(out$first_seen_censored, c(1L, 1L))
})

test_that("apply_fork_guard censors a template-seeded marker on a non-fork, leaves the rest exact", {
  ev <- rbind(gd("claude", "D", "CLAUDE.md"), gd("cursor", "D", ".cursor"))
  out <- apply_fork_guard(ev, is_fork = FALSE, parent = NA_character_,
                          first_commit_touches = c("CLAUDE.md"))
  expect_equal(out$first_seen_censored[out$marker == "CLAUDE.md"], 1L)
  expect_equal(out$first_seen_censored[out$marker == ".cursor"], 0L)
})

test_that("apply_fork_guard never censors a non-Tier-D row", {
  ev <- rbind(gd("claude", "B", "B"), gd("claude", "D", "CLAUDE.md"))
  out <- apply_fork_guard(ev, is_fork = TRUE, parent = "up/stream", first_commit_touches = character(0))
  expect_equal(out$first_seen_censored[out$tier == "B"], 0L)   # commit-tier onset untouched
  expect_equal(out$first_seen_censored[out$tier == "D"], 1L)
})

test_that("apply_fork_guard passes an empty evidence frame through unchanged", {
  ev <- .ai_empty_evidence()
  expect_equal(nrow(apply_fork_guard(ev, FALSE, NA_character_, character(0))), 0)
})

test_that("build_ai_detail collapses per tool: reducer picks the tighter onset, unions tiers, ORs authored", {
  ev <- data.frame(
    tool     = c("claude", "claude", "cursor"),
    tier     = c("D", "B", "D"),
    marker   = c(".claude", "B", ".cursor"),
    agnostic = FALSE,
    first_seen_censored = c(0L, 0L, 1L),   # cursor .cursor was fork-censored upstream
    authored = c(0L, 1L, 0L),
    stringsAsFactors = FALSE)
  onsets <- data.frame(
    tool   = c("claude", "claude", "cursor"),
    marker = c(".claude", "B", ".cursor"),
    first_seen_date = c("2024-06-01", "2024-03-01", "2022-01-01"),
    first_seen_censored = c(0L, 0L, 0L),
    stringsAsFactors = FALSE)
  out <- build_ai_detail("github.com/o/r", ev, onsets, last_confirmed = "2026-07-15")
  expect_setequal(out$tool, c("claude", "cursor"))
  cl <- out[out$tool == "claude", ]
  expect_equal(cl$first_seen_date, "2024-03-01")                     # exact B beats D marker date
  expect_equal(cl$first_seen_censored, 0L)
  expect_setequal(strsplit(cl$evidence_tiers, ",")[[1]], c("B", "D"))
  expect_equal(cl$authored, 1L)
  expect_equal(cl$last_confirmed_date, "2026-07-15")
  cu <- out[out$tool == "cursor", ]
  expect_equal(cu$first_seen_censored, 1L)                           # fork-guard censoring survives
  expect_equal(cu$first_seen_date, "2022-01-01")
  expect_true(all(c("repo_id", "tool", "first_seen_date", "first_seen_censored",
                    "evidence_tiers", "authored", "last_confirmed_date") %in% names(out)))
})

test_that("build_ai_detail returns a typed 0-row frame for no evidence and tolerates NULL onsets", {
  out <- build_ai_detail("github.com/o/r", NULL, NULL, "2026-07-15")
  expect_equal(nrow(out), 0)
  expect_true(all(c("repo_id", "tool", "first_seen_date", "first_seen_censored",
                    "evidence_tiers", "authored", "last_confirmed_date") %in% names(out)))
  ev <- data.frame(tool = "claude", tier = "D", marker = ".claude", agnostic = FALSE,
                   stringsAsFactors = FALSE)
  nulled <- build_ai_detail("github.com/o/r", ev, NULL, "2026-07-15")   # onsets NULL -> NA date
  expect_equal(nulled$tool, "claude")
  expect_true(is.na(nulled$first_seen_date))
})

test_that("assemble_repo_evidence unions Tier-D markers, ignore tokens, and post-cutoff agent PRs", {
  tree <- list(root_entries = c(".claude", "DESCRIPTION"), github_entries = character(0),
               is_fork = FALSE, parent = NA_character_,
               gitignore_lines = c(".aiderignore", "*.o"), rbuildignore_lines = character(0))
  pr <- list(prs = data.frame(
    login = c("octocat", "Copilot", "cursor[bot]"),
    typename = c("User", "Bot", "Bot"),
    created_at = c("2019-01-01T00:00:00Z", "2024-05-01T00:00:00Z", "2022-06-01T00:00:00Z"),
    stringsAsFactors = FALSE), has_next = FALSE)
  ev <- assemble_repo_evidence(tree, pr)
  expect_true("claude" %in% ev$tool[ev$tier == "D"])            # .claude marker
  expect_true("aider" %in% ev$tool[ev$tier == "D"])             # .aiderignore token
  expect_true("copilot" %in% ev$tool[ev$tier == "PR"])          # post-cutoff agent PR
  expect_false("cursor" %in% ev$tool[ev$tier == "PR"])          # cursor[bot] PR predates the cutoff -> rejected
})

test_that("repo_has_ai_signal is the any-evidence gate; absence never counts as clean", {
  expect_false(repo_has_ai_signal(.ai_empty_evidence()))
  expect_false(repo_has_ai_signal(NULL))
  ev <- assemble_repo_evidence(list(root_entries = "CLAUDE.md"), NULL)
  expect_true(repo_has_ai_signal(ev))
})

test_that("earliest_agent_pr_date returns the earliest post-cutoff agent createdAt, NA otherwise", {
  pr <- list(prs = data.frame(
    login = c("devin-ai-integration[bot]", "Copilot", "octocat"),
    typename = c("Bot", "Bot", "User"),
    created_at = c("2024-09-01T00:00:00Z", "2024-03-01T00:00:00Z", "2018-01-01T00:00:00Z"),
    stringsAsFactors = FALSE), has_next = TRUE)
  expect_equal(earliest_agent_pr_date(pr), "2024-03-01T00:00:00Z")
  none <- list(prs = data.frame(login = "octocat", typename = "User",
                                created_at = "2024-01-01T00:00:00Z", stringsAsFactors = FALSE),
               has_next = FALSE)
  expect_true(is.na(earliest_agent_pr_date(none)))
  expect_true(is.na(earliest_agent_pr_date(NULL)))
})

test_that("build_onset_map maps Tier-D markers and ignore tokens to exact onsets", {
  ev <- data.frame(tool = c("claude", "aider"), tier = c("D", "D"),
                   marker = c("CLAUDE.md", "ignore:.aiderignore"),
                   agnostic = c(FALSE, FALSE), stringsAsFactors = FALSE)
  om <- build_onset_map(ev, marker_dates = list("CLAUDE.md" = "2024-02-01T00:00:00Z",
                                                ".aiderignore" = "2023-11-01T00:00:00Z"))
  expect_equal(om$first_seen_date[om$marker == "CLAUDE.md"], "2024-02-01T00:00:00Z")
  expect_equal(om$first_seen_date[om$marker == "ignore:.aiderignore"], "2023-11-01T00:00:00Z")
  expect_true(all(om$first_seen_censored == 0L))            # marker onsets are exact
})

test_that("build_onset_map records a PR onset exact and a commit onset per its confirmed flag", {
  ev <- data.frame(
    tool = c("copilot", "claude", "cursor"), tier = c("PR", "A", "B"),
    marker = c("PR", "A", "B"), agnostic = FALSE, stringsAsFactors = FALSE)
  co <- data.frame(tool = c("claude", "cursor"), tier = c("A", "B"),
                   first_seen_date = c("2023-09-01T00:00:00Z", "2023-01-05T00:00:00Z"),
                   confirmed = c(TRUE, FALSE), stringsAsFactors = FALSE)
  om <- build_onset_map(ev, commit_onsets = co, pr_date = "2024-04-01T00:00:00Z")
  expect_equal(om$first_seen_date[om$marker == "PR"], "2024-04-01T00:00:00Z")
  expect_equal(om$first_seen_censored[om$marker == "PR"], 0L)            # PR event -> exact
  expect_equal(om$first_seen_censored[om$tool == "claude"], 0L)         # confirmed -> exact
  expect_equal(om$first_seen_censored[om$tool == "cursor"], 1L)         # unconfirmed -> floor
})

test_that("build_onset_map leaves an unresolved onset NA and feeds build_ai_detail", {
  ev <- data.frame(tool = "claude", tier = "D", marker = "CLAUDE.md",
                   agnostic = FALSE, stringsAsFactors = FALSE)
  om <- build_onset_map(ev)                                             # no dates supplied
  expect_true(is.na(om$first_seen_date))
  # marker onset earlier than a floor from a commit search: the reducer keeps the exact
  ev2 <- data.frame(tool = c("claude", "claude"), tier = c("D", "B"),
                    marker = c("CLAUDE.md", "B"), agnostic = FALSE, stringsAsFactors = FALSE)
  om2 <- build_onset_map(ev2, marker_dates = list("CLAUDE.md" = "2024-01-01T00:00:00Z"),
    commit_onsets = data.frame(tool = "claude", tier = "B",
      first_seen_date = "2023-06-01T00:00:00Z", confirmed = TRUE, stringsAsFactors = FALSE))
  detail <- build_ai_detail("github.com/o/r", ev2, om2, "2026-07-16")
  expect_equal(nrow(detail), 1)                                        # collapsed per tool
  expect_equal(detail$first_seen_date, "2023-06-01T00:00:00Z")         # tighter (earlier) exact wins
  expect_setequal(strsplit(detail$evidence_tiers, ",")[[1]], c("B", "D"))
})

test_that("select_incremental_repos keeps only repos with a tool not in the published detail", {
  flagged <- data.frame(
    repo_id = c("github.com/a/x", "github.com/b/y", "github.com/c/z"),
    owner = c("a", "b", "c"), name = c("x", "y", "z"),
    node_id = c("R_a", "R_b", "R_c"), is_fork = 0L,
    parent = NA_character_, pr_onset_date = NA_character_, stringsAsFactors = FALSE)
  evidence <- data.frame(
    repo_id = c("github.com/a/x", "github.com/b/y", "github.com/c/z", "github.com/c/z"),
    tool = c("claude", "cursor", "claude", "copilot"),
    tier = c("D", "D", "D", "PR"),
    marker = c("CLAUDE.md", ".cursor", "CLAUDE.md", "PR"),
    agnostic = 0L, stringsAsFactors = FALSE)
  # A/claude and C/claude are already published; B/cursor and C/copilot are new.
  published <- data.frame(
    repo_id = c("github.com/a/x", "github.com/c/z"), tool = c("claude", "claude"),
    first_seen_date = c("2024-01-01", "2024-02-01"), first_seen_censored = 0L,
    evidence_tiers = "D", authored = 0L, last_confirmed_date = c("2024-01-01", "2024-02-01"),
    stringsAsFactors = FALSE)

  keep <- select_incremental_repos(flagged, evidence, published)
  expect_setequal(keep, c("github.com/b/y", "github.com/c/z"))  # B new tool, C adopted a 2nd
  expect_false("github.com/a/x" %in% keep)                      # all A's tools already onset
})

test_that("select_incremental_repos treats an empty published detail as everything-is-new", {
  flagged <- data.frame(repo_id = "github.com/a/x", owner = "a", name = "x",
                        node_id = "R_a", is_fork = 0L, parent = NA_character_,
                        pr_onset_date = NA_character_, stringsAsFactors = FALSE)
  evidence <- data.frame(repo_id = "github.com/a/x", tool = "claude", tier = "D",
                         marker = "CLAUDE.md", agnostic = 0L, stringsAsFactors = FALSE)
  keep <- select_incremental_repos(flagged, evidence, .ai_empty_signals())
  expect_equal(keep, "github.com/a/x")
})

test_that("select_incremental_repos treats a newly-adopted agents-md as a new tool (no special-casing)", {
  flagged <- data.frame(repo_id = "github.com/a/x", owner = "a", name = "x",
                        node_id = "R_a", is_fork = 0L, parent = NA_character_,
                        pr_onset_date = NA_character_, stringsAsFactors = FALSE)
  evidence <- data.frame(repo_id = "github.com/a/x", tool = "agents-md", tier = "D",
                         marker = "AGENTS.md", agnostic = 1L, stringsAsFactors = FALSE)
  # agents-md not yet published -> selected; then published -> not re-selected.
  expect_equal(select_incremental_repos(flagged, evidence, .ai_empty_signals()),
               "github.com/a/x")
  published <- data.frame(repo_id = "github.com/a/x", tool = "agents-md",
                          first_seen_date = "2024-01-01", first_seen_censored = 0L,
                          evidence_tiers = "D", authored = 0L,
                          last_confirmed_date = "2024-01-01", stringsAsFactors = FALSE)
  expect_equal(select_incremental_repos(flagged, evidence, published), character(0))
})

test_that("select_confirmation_rows emits last-confirmed-only rows for already-published tools still detected", {
  evidence <- data.frame(
    repo_id = c("github.com/a/x", "github.com/b/y", "github.com/c/z", "github.com/c/z"),
    tool = c("claude", "cursor", "claude", "copilot"),
    tier = c("D", "D", "D", "PR"),
    marker = c("CLAUDE.md", ".cursor", "CLAUDE.md", "PR"),
    agnostic = 0L, stringsAsFactors = FALSE)
  # A/claude and C/claude are already published; B/cursor and C/copilot are new (no
  # confirmation row for those - select_incremental_repos already re-onsets them).
  published <- data.frame(
    repo_id = c("github.com/a/x", "github.com/c/z"), tool = c("claude", "claude"),
    first_seen_date = c("2024-01-01", "2024-02-01"), first_seen_censored = 0L,
    evidence_tiers = "D", authored = 0L, last_confirmed_date = c("2024-01-01", "2024-02-01"),
    stringsAsFactors = FALSE)

  rows <- select_confirmation_rows(evidence, published, "2026-07-16")
  expect_setequal(paste(rows$repo_id, rows$tool),
                  c("github.com/a/x claude", "github.com/c/z claude"))
  expect_true(all(is.na(rows$first_seen_date)))
  expect_true(all(is.na(rows$evidence_tiers)))
  expect_equal(rows$first_seen_censored, c(0L, 0L))
  expect_equal(rows$authored, c(0L, 0L))
  expect_equal(rows$last_confirmed_date, rep("2026-07-16", 2))
})

test_that("select_confirmation_rows returns the empty 7-col frame when nothing is published yet", {
  evidence <- data.frame(repo_id = "github.com/a/x", tool = "claude", tier = "D",
                         marker = "CLAUDE.md", agnostic = 0L, stringsAsFactors = FALSE)
  rows <- select_confirmation_rows(evidence, .ai_empty_signals(), "2026-07-16")
  expect_equal(nrow(rows), 0)
  expect_equal(names(rows), names(.ai_empty_signals()))
})

test_that("a confirmation row reduces against the prior published row: onset frozen, last_confirmed advances", {
  prior <- data.frame(repo_id = "github.com/a/x", tool = "claude",
                      first_seen_date = "2024-01-01", first_seen_censored = 0L,
                      evidence_tiers = "D", authored = 0L,
                      last_confirmed_date = "2024-01-01", stringsAsFactors = FALSE)
  evidence <- data.frame(repo_id = "github.com/a/x", tool = "claude", tier = "D",
                         marker = "CLAUDE.md", agnostic = 0L, stringsAsFactors = FALSE)
  confirm <- select_confirmation_rows(evidence, prior, "2026-07-16")

  reduced <- ai_onset_reducer(prior, confirm)
  expect_equal(nrow(reduced), 1)
  expect_equal(reduced$first_seen_date, "2024-01-01")      # immutable onset untouched
  expect_equal(reduced$first_seen_censored, 0L)
  expect_equal(reduced$evidence_tiers, "D")                # prior tier preserved
  expect_equal(reduced$authored, 0L)
  expect_equal(reduced$last_confirmed_date, "2026-07-16")  # advances via max()
})

test_that("marker_repo_path prepends .github/ only for github-located markers", {
  # github-located file marker: its real repo path lives under .github/
  expect_equal(marker_repo_path("copilot-instructions.md"), ".github/copilot-instructions.md")
  # root file marker: unchanged
  expect_equal(marker_repo_path("CLAUDE.md"), "CLAUDE.md")
  # root directory marker: unchanged (GraphQL history(path:) resolves a directory directly)
  expect_equal(marker_repo_path(".claude"), ".claude")
  expect_equal(marker_repo_path(".cursor"), ".cursor")
  # an unknown marker (not in AI_MARKERS) is returned verbatim
  expect_equal(marker_repo_path("not-a-marker"), "not-a-marker")
})
