test_that("classify_tree_markers matches root and .github entries, tags agents-md agnostic", {
  out <- classify_tree_markers(c("CLAUDE.md", ".cursor", "README.md", "AGENTS.md"),
                               c("copilot-instructions.md", "workflows"))
  expect_setequal(out$tool, c("claude", "cursor", "copilot", "agents-md"))
  expect_true(all(out$tier == "D"))
  expect_true(out$agnostic[out$tool == "agents-md"])
  expect_false(any(out$agnostic[out$tool != "agents-md"]))
})

test_that("classify_tree_markers does not match a github-located marker at root", {
  out <- classify_tree_markers(c("copilot-instructions.md"), character(0))
  expect_equal(nrow(out), 0)   # copilot marker only counts inside .github
})

test_that("classify_tree_markers returns typed empty frame when nothing matches", {
  out <- classify_tree_markers(c("R", "man", "DESCRIPTION"), c("workflows"))
  expect_equal(nrow(out), 0)
  expect_true(all(c("tool","tier","marker","agnostic") %in% names(out)))
})

test_that("scan_ignore_tokens anchors whole entries and ignores comments and word-substrings", {
  gi <- c("# ai stuff", ".aiderignore", "*.o", "codex_output/")   # codex_output must NOT match codex
  rb <- c("^\\.cursor$", ".cursorignore")
  out <- scan_ignore_tokens(gi, rb)
  expect_true("aider" %in% out$tool)                         # .aiderignore is a real AI_MARKERS aider path
  expect_true("cursor" %in% out$tool)
  expect_false("codex" %in% out$tool)                        # substring collision rejected
  expect_true(all(grepl("^ignore:", out$marker)))
})

test_that("scan_ignore_tokens returns typed empty frame on no match", {
  out <- scan_ignore_tokens(c("*.tmp", "# nothing"), character(0))
  expect_equal(nrow(out), 0)
  expect_true(all(c("tool","tier","marker","agnostic") %in% names(out)))
})

test_that("match_bot_identity matches allowlist exactly, rejects denylist and lookalikes", {
  out <- match_bot_identity(c("NoReply@Anthropic.com", "someone@example.com"),
                            c("dependabot[bot]", "devin-ai-integration[bot]"))
  expect_setequal(out$tool, c("claude", "devin"))
  expect_true(all(out$tier == "A"))
  # a lookalike substring must not match
  expect_equal(nrow(match_bot_identity("noreply@anthropic.com.evil.net", character(0))), 0)
  # denylisted bot alone yields nothing
  expect_equal(nrow(match_bot_identity(character(0), "renovate[bot]")), 0)
})

test_that("scan_trailers requires the canonical identity, rejects a human named Claude", {
  yes <- scan_trailers(c("feat: x\n\nCo-authored-by: Claude <noreply@anthropic.com>"))
  expect_equal(yes$tool, "claude"); expect_equal(yes$tier, "B")
  no <- scan_trailers("fix\n\nCo-authored-by: Claude Dupont <claude@univ.fr>")
  expect_equal(nrow(no), 0)
  expect_equal(scan_trailers("chore: generated by Replit")$tool, "replit")
})

test_that("match_author_suffix flags the (aider) suffix only", {
  expect_equal(match_author_suffix(c("Jane Doe (aider)", "Bob"))$tool, "aider")
  expect_equal(nrow(match_author_suffix("aidermann")), 0)
})

test_that("detect_pr_agents matches agent logins, never generic bots", {
  out <- detect_pr_agents(c("Copilot", "dependabot[bot]", "cursor[bot]"))
  expect_setequal(out$tool, c("copilot", "cursor"))
  expect_true(all(out$tier == "PR"))
})

mk <- function(tool, date, censored = 0L, tiers, authored = 0L, agnostic = FALSE)
  data.frame(tool = tool, first_seen_date = date, first_seen_censored = censored,
             evidence_tiers = tiers, authored = authored, agnostic = agnostic,
             stringsAsFactors = FALSE)

test_that("naming threshold: Tier A alone passes, lone Tier D fails, two tiers pass", {
  expect_true(meets_naming_threshold(mk("claude", "2024-01-01", tiers = "A")))
  expect_false(meets_naming_threshold(mk("cursor", "2024-01-01", tiers = "D")))
  expect_true(meets_naming_threshold(mk("claude", "2024-01-01", tiers = "D,B")))
  # agents-md alone never satisfies (agnostic, single tier)
  expect_false(meets_naming_threshold(mk("agents-md", "2024-01-01", tiers = "D", agnostic = TRUE)))
})

test_that("order_ai_tools sorts by date then censored then tier then name, excludes agents-md", {
  rows <- rbind(
    mk("copilot",   "2024-11-01", tiers = "D"),
    mk("claude",    "2024-06-01", tiers = "A"),
    mk("agents-md", "2024-01-01", tiers = "D", agnostic = TRUE),
    mk("cursor",    "2025-03-01", tiers = "D"))
  expect_equal(order_ai_tools(rows), c("claude", "copilot", "cursor"))  # agents-md dropped, chronological
})

test_that("order_ai_tools tie-break: same date -> stronger tier, then name", {
  rows <- rbind(
    mk("cursor", "2024-01-01", tiers = "D"),
    mk("claude", "2024-01-01", tiers = "A"))
  expect_equal(order_ai_tools(rows)[1], "claude")   # A beats D on the same date
})
