test_that("classify_tree_markers matches root and .github entries, tags agents-md agnostic", {
  out <- classify_tree_markers(c("CLAUDE.md", ".cursor", "README.md", "AGENTS.md"),
                               c("copilot-instructions.md", "workflows"))
  expect_setequal(out$tool, c("claude", "cursor", "copilot", "agents-md"))
  expect_true(all(out$tier == "D"))
  expect_true(out$agnostic[out$tool == "agents-md"])
  expect_false(any(out$agnostic[out$tool != "agents-md"]))
})

test_that("classify_tree_markers does not match a github-located marker at root", {
  out <- classify_tree_markers(c("copilot-instructions.md"), character(0))
  expect_equal(nrow(out), 0)   # copilot marker only counts inside .github
})

test_that("classify_tree_markers returns typed empty frame when nothing matches", {
  out <- classify_tree_markers(c("R", "man", "DESCRIPTION"), c("workflows"))
  expect_equal(nrow(out), 0)
  expect_true(all(c("tool","tier","marker","agnostic") %in% names(out)))
})

test_that("scan_ignore_tokens anchors whole entries and ignores comments and word-substrings", {
  gi <- c("# ai stuff", ".aiderignore", "*.o", "codex_output/")   # codex_output must NOT match codex
  rb <- c("^\\.cursor$", ".cursorignore")
  out <- scan_ignore_tokens(gi, rb)
  expect_true("aider" %in% out$tool)                         # .aiderignore is a real AI_MARKERS aider path
  expect_true("cursor" %in% out$tool)
  expect_false("codex" %in% out$tool)                        # substring collision rejected
  expect_true(all(grepl("^ignore:", out$marker)))
})

test_that("scan_ignore_tokens returns typed empty frame on no match", {
  out <- scan_ignore_tokens(c("*.tmp", "# nothing"), character(0))
  expect_equal(nrow(out), 0)
  expect_true(all(c("tool","tier","marker","agnostic") %in% names(out)))
})

test_that("match_bot_identity matches allowlist exactly, rejects denylist and lookalikes", {
  out <- match_bot_identity(c("NoReply@Anthropic.com", "someone@example.com"),
                            c("dependabot[bot]", "devin-ai-integration[bot]"))
  expect_setequal(out$tool, c("claude", "devin"))
  expect_true(all(out$tier == "A"))
  # a lookalike substring must not match
  expect_equal(nrow(match_bot_identity("noreply@anthropic.com.evil.net", character(0))), 0)
  # denylisted bot alone yields nothing
  expect_equal(nrow(match_bot_identity(character(0), "renovate[bot]")), 0)
})

test_that("scan_trailers requires the canonical identity, rejects a human named Claude", {
  yes <- scan_trailers(c("feat: x\n\nCo-authored-by: Claude <noreply@anthropic.com>"))
  expect_equal(yes$tool, "claude"); expect_equal(yes$tier, "B")
  no <- scan_trailers("fix\n\nCo-authored-by: Claude Dupont <claude@univ.fr>")
  expect_equal(nrow(no), 0)
  expect_equal(scan_trailers("chore: generated by Replit")$tool, "replit")
})

test_that("match_author_suffix flags the (aider) suffix only", {
  expect_equal(match_author_suffix(c("Jane Doe (aider)", "Bob"))$tool, "aider")
  expect_equal(nrow(match_author_suffix("aidermann")), 0)
})

test_that("detect_pr_agents matches agent logins, never generic bots", {
  out <- detect_pr_agents(c("Copilot", "dependabot[bot]", "cursor[bot]"))
  expect_setequal(out$tool, c("copilot", "cursor"))
  expect_true(all(out$tier == "PR"))
})

mk <- function(tool, date, censored = 0L, tiers, authored = 0L, agnostic = FALSE)
  data.frame(tool = tool, first_seen_date = date, first_seen_censored = censored,
             evidence_tiers = tiers, authored = authored, agnostic = agnostic,
             stringsAsFactors = FALSE)

test_that("naming threshold: Tier A alone passes, lone Tier D fails, two tiers pass", {
  expect_true(meets_naming_threshold(mk("claude", "2024-01-01", tiers = "A")))
  expect_false(meets_naming_threshold(mk("cursor", "2024-01-01", tiers = "D")))
  expect_true(meets_naming_threshold(mk("claude", "2024-01-01", tiers = "D,B")))
  # agents-md alone never satisfies (agnostic, single tier)
  expect_false(meets_naming_threshold(mk("agents-md", "2024-01-01", tiers = "D", agnostic = TRUE)))
})

test_that("order_ai_tools sorts by date then censored then tier then name, excludes agents-md", {
  rows <- rbind(
    mk("copilot",   "2024-11-01", tiers = "D"),
    mk("claude",    "2024-06-01", tiers = "A"),
    mk("agents-md", "2024-01-01", tiers = "D", agnostic = TRUE),
    mk("cursor",    "2025-03-01", tiers = "D"))
  expect_equal(order_ai_tools(rows), c("claude", "copilot", "cursor"))  # agents-md dropped, chronological
})

test_that("order_ai_tools tie-break: same date -> stronger tier, then name", {
  rows <- rbind(
    mk("cursor", "2024-01-01", tiers = "D"),
    mk("claude", "2024-01-01", tiers = "A"))
  expect_equal(order_ai_tools(rows)[1], "claude")   # A beats D on the same date
})

row <- function(tool, date, cens, tiers, auth, last, repo = "github.com/o/r")
  data.frame(repo_id = repo, tool = tool, first_seen_date = date, first_seen_censored = cens,
             evidence_tiers = tiers, authored = auth, last_confirmed_date = last,
             stringsAsFactors = FALSE)

test_that("reducer: exact replaces a looser floor, tiers union, authored OR, last_confirmed max", {
  prior <- row("claude", "2024-06-01", 1L, "D", 0L, "2024-06-01")            # censored floor <= 2024-06-01
  inc   <- row("claude", "2024-03-01", 0L, "B", 1L, "2025-01-01")            # exact, earlier than floor
  out <- ai_onset_reducer(prior, inc)
  expect_equal(out$first_seen_date, "2024-03-01")
  expect_equal(out$first_seen_censored, 0L)
  expect_setequal(strsplit(out$evidence_tiers, ",")[[1]], c("B", "D"))
  expect_equal(out$authored, 1L)
  expect_equal(out$last_confirmed_date, "2025-01-01")
})

test_that("reducer: two floors tighten to the min; two exacts take the min", {
  o <- ai_onset_reducer(row("cursor","2023-01-01",1L,"D",0L,"2023-01-01"),
                        row("cursor","2022-06-01",1L,"D",0L,"2022-06-01"))
  expect_equal(o$first_seen_date, "2022-06-01"); expect_equal(o$first_seen_censored, 1L)
  e <- ai_onset_reducer(row("cursor","2022-01-01",0L,"D",0L,"2022-01-01"),
                        row("cursor","2021-05-05",0L,"B",0L,"2021-05-05"))
  expect_equal(e$first_seen_date, "2021-05-05"); expect_equal(e$first_seen_censored, 0L)
})

test_that("reducer: an exact LATER than a floor is a contradiction - keep the floor and warn", {
  expect_warning(
    o <- ai_onset_reducer(row("claude","2023-01-01",1L,"D",0L,"2023-01-01"),   # floor <= 2023-01-01
                          row("claude","2024-05-05",0L,"B",0L,"2024-05-05")),   # exact 2024 (contradicts)
    "contradiction")
  expect_equal(o$first_seen_date, "2023-01-01"); expect_equal(o$first_seen_censored, 1L)
})

test_that("reducer keeps distinct tools as distinct rows", {
  o <- ai_onset_reducer(row("claude","2024-01-01",0L,"A",0L,"2024-01-01"),
                        row("cursor","2024-02-01",0L,"D",0L,"2024-02-01"))
  expect_equal(nrow(o), 2)
})

test_that("build_ai_rollups names only threshold-met repos, excludes agents-md from counts", {
  ai <- rbind(
    # repo A: claude Tier A (nameable) + agents-md agnostic
    data.frame(repo_id="github.com/a/a", tool="claude", first_seen_date="2024-06-01",
               first_seen_censored=0L, evidence_tiers="A", authored=1L,
               last_confirmed_date="2025-01-01", stringsAsFactors=FALSE),
    data.frame(repo_id="github.com/a/a", tool="agents-md", first_seen_date="2024-01-01",
               first_seen_censored=0L, evidence_tiers="D", authored=0L,
               last_confirmed_date="2024-01-01", stringsAsFactors=FALSE),
    data.frame(repo_id="github.com/a/a", tool="cursor", first_seen_date="2025-03-01",
               first_seen_censored=0L, evidence_tiers="D,B", authored=0L,
               last_confirmed_date="2025-03-01", stringsAsFactors=FALSE),
    # repo B: lone Tier D -> below threshold, omitted
    data.frame(repo_id="github.com/b/b", tool="copilot", first_seen_date="2024-02-01",
               first_seen_censored=0L, evidence_tiers="D", authored=0L,
               last_confirmed_date="2024-02-01", stringsAsFactors=FALSE))
  out <- build_ai_rollups(ai)
  expect_equal(out$repo_id, "github.com/a/a")            # only the nameable repo
  expect_true(out$ai_markers_detected)
  expect_equal(out$ai_first_tool, "claude")             # earliest non-agnostic
  expect_equal(out$ai_first_date, "2024-06-01")
  expect_equal(out$ai_tool_count, 2L)                   # claude + cursor, agents-md excluded
  expect_equal(out$ai_tools, "claude,cursor")
  expect_equal(out$ai_latest_tool, "cursor")
  expect_equal(out$ai_latest_date, "2025-03-01")
})

test_that("build_ai_rollups returns a typed empty frame when nothing is nameable", {
  ai <- data.frame(repo_id="github.com/b/b", tool="copilot", first_seen_date="2024-02-01",
                   first_seen_censored=0L, evidence_tiers="D", authored=0L,
                   last_confirmed_date="2024-02-01", stringsAsFactors=FALSE)
  out <- build_ai_rollups(ai)
  expect_equal(nrow(out), 0)
  expect_true(all(c("repo_id","ai_markers_detected","ai_first_tool","ai_first_date",
                    "ai_tool_count","ai_tools","ai_latest_tool","ai_latest_date") %in% names(out)))
})

test_that("order_ai_tools does not crash on an unknown evidence_tiers code and sorts it last", {
  rows <- rbind(
    mk("claude", "2024-01-01", tiers = "A"),
    mk("mystery", "2024-01-01", tiers = "Z"))   # unknown tier code -> rank falls back to 99
  out <- order_ai_tools(rows)
  expect_equal(out, c("claude", "mystery"))     # same date: unknown-tier tool included, sorted last on rank
})

test_that("reducer: authored is 0L (never NA) when one input row has authored = NA and none is 1", {
  o <- ai_onset_reducer(row("claude", "2024-01-01", 0L, "A", NA_integer_, "2024-01-01"),
                        row("claude", "2024-02-01", 0L, "B", 0L, "2024-02-01"))
  expect_identical(o$authored, 0L)
  expect_false(is.na(o$authored))
})

test_that("ai_onset_reducer(NULL, NULL) returns a typed 0-row frame, not NULL", {
  out <- ai_onset_reducer(NULL, NULL)
  expect_false(is.null(out))
  expect_equal(nrow(out), 0)
  expect_true(all(c("repo_id", "tool", "first_seen_date", "first_seen_censored",
                    "evidence_tiers", "authored", "last_confirmed_date") %in% names(out)))
})
